ALTER TABLE `fcs_product`
  DROP `id_supplier`,
  DROP `id_shop_default`,
  DROP `id_tax_rules_group`,
  DROP `on_sale`,
  DROP `online_only`,
  DROP `ean13`,
  DROP `upc`,
  DROP `ecotax`,
  DROP `minimal_quantity`,
  DROP `wholesale_price`,
  DROP `unit_price_ratio`,
  DROP `additional_shipping_cost`,
  DROP `supplier_reference`,
  DROP `location`,
  DROP `width`,
  DROP `height`,
  DROP `depth`,
  DROP `weight`,
  DROP `out_of_stock`,
  DROP `quantity_discount`,
  DROP `customizable`,
  DROP `uploadable_files`,
  DROP `text_fields`,
  DROP `redirect_type`,
  DROP `id_product_redirected`,
  DROP `available_for_order`,
  DROP `available_date`,
  DROP `condition`,
  DROP `reference`,
  DROP `show_price`,
  DROP `indexed`,
  DROP `visibility`,
  DROP `cache_is_pack`,
  DROP `cache_has_attachments`,
  DROP `is_virtual`,
  DROP `cache_default_attribute`,
  DROP `advanced_stock_management`,
  DROP `pack_stock_type`;

ALTER TABLE `fcs_product_attribute`
  DROP `reference`,
  DROP `supplier_reference`,
  DROP `location`,
  DROP `ean13`,
  DROP `upc`,
  DROP `wholesale_price`,
  DROP `ecotax`,
  DROP `weight`,
  DROP `unit_price_impact`,
  DROP `minimal_quantity`,
  DROP `available_date`;

ALTER TABLE `fcs_product_attribute_shop`
  DROP `wholesale_price`,
  DROP `ecotax`,
  DROP `weight`,
  DROP `unit_price_impact`,
  DROP `minimal_quantity`,
  DROP `available_date`;

ALTER TABLE `fcs_product_lang`
  DROP `meta_description`,
  DROP `meta_keywords`,
  DROP `meta_title`,
  DROP `available_now`,
  DROP `available_later`;

ALTER TABLE `fcs_product_shop`
  DROP `id_tax_rules_group`,
  DROP `on_sale`,
  DROP `online_only`,
  DROP `ecotax`,
  DROP `minimal_quantity`,
  DROP `wholesale_price`,
  DROP `unit_price_ratio`,
  DROP `additional_shipping_cost`,
  DROP `customizable`,
  DROP `uploadable_files`,
  DROP `text_fields`,
  DROP `redirect_type`,
  DROP `id_product_redirected`,
  DROP `available_for_order`,
  DROP `available_date`,
  DROP `condition`,
  DROP `show_price`,
  DROP `indexed`,
  DROP `visibility`,
  DROP `cache_default_attribute`,
  DROP `advanced_stock_management`,
  DROP `pack_stock_type`;
