tasks:
  - name: Docker
    init: |
      docker compose pull
      docker compose up
  - name: Bash
ports:
  - port: 8001
    onOpen: notify
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 3310
    onOpen: ignore
  - port: 3311
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true