tasks:
  - init: |
      docker compose pull
      docker compose up
  - command: |
      docker compose exec -T database-dev mysql --port 3310 foodcoopshop-dev < ./config/sql/_installation/clean-db-structure.sql
      docker compose exec -T database-dev mysql --port 3310 foodcoopshop-dev < ./tests/config/sql/test-db-data.sql
      docker compose run --rm composer install
      docker exec -w /var/www/html fcs-php-nginx bash ./devtools/set-permissions.sh
      docker exec -w /var/www/html fcs-php-nginx bash ./devtools/setup-dev-config.sh
      docker compose run -w /var/www/html/webroot --rm node npm install
      docker exec -w /var/www/html fcs-php-nginx bash ./bin/cake npm_post_install
      echo "The FoodCoopShop application is ready to use."
      echo "@see https://foodcoopshop.github.io/en/docker-dev-environment.html'"
ports:
  - port: 8001
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
  - port: 3310
    onOpen: ignore
  - port: 3311
    onOpen: ignore
    