tasks:
  - init: |
      docker compose pull
      docker compose up
      echo "Please run 'bash ./devtools/gitpod-init.sh' to complete setting up your dev environment."
    command: |
      echo "@see https://foodcoopshop.github.io/en/docker-dev-environment.html"
ports:
  - port: 8001
    onOpen: browser
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 3310
    onOpen: ignore
  - port: 3311
    onOpen: ignore
    