tasks:
  - name: Docker
    init: |
      docker compose pull
      docker compose up
  - name: bash
    command: |
      echo "When all containers are up and running, open your bash terminal (not: Docker) and run: bash ./devtools/setup-dev-init.sh"
      echo "@see https://foodcoopshop.github.io/en/docker-dev-environment.html"
ports:
  - port: 8001
    onOpen: notify
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 3310
    onOpen: ignore
  - port: 3311
    onOpen: ignore
    