tasks:
  - name: Docker
    init: |
      docker compose pull
      docker compose up
  - name: bash
    command: |
      bash ./devtools/gitpod-init.sh
      echo "Please run 'bash ./devtools/gitpod-init.sh' to complete setting up your dev environment."
      echo "@see https://foodcoopshop.github.io/en/docker-dev-environment.html"
ports:
  - port: 8001
    onOpen: open-browser
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore
  - port: 3310
    onOpen: ignore
  - port: 3311
    onOpen: ignore
    