#The provided docker should NOT BE USED IN PRODUCTION ENVIRONMENTS!

services:

  php-nginx:
    build: .
    container_name: fcs.php
    restart: always
    user: ${CURRENT_UID}
    environment:
      WEB_DOCUMENT_ROOT: /app/webroot
      PHP_UPLOAD_MAX_FILESIZE: 200M
      PHP_POST_MAX_SIZE: 200M
    volumes:
      - ./:/app
    ports:
      - "8001:80"
    networks:
      default:
        aliases:
           # add "127.0.0.1 foodcoopshop.test" to your hosts file to use http://foodcoopshop.test:8001
          - foodcoopshop.test
      fcs:

  database-dev:
    image: mysql:8.0
    container_name: fcs.database.dev
    restart: always
    ports:
      - '3320:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: foodcoopshop-dev
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3320
    volumes:
      - db-dev-data:/var/lib/mysql
    networks:
      - fcs

  database-test:
    image: mysql:8.0
    container_name: fcs.database.test
    restart: always
    tmpfs: /var/lib/mysql:exec,size=1G #smaller size (eg. 256M) lead to failing tests
    ports:
      - '3321:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: foodcoopshop-test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3321
    networks:
      - fcs

  phpmyadmin-dev:
    depends_on:
      - database-dev
    image: phpmyadmin/phpmyadmin
    container_name: fcs.phpmyadmin.dev
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database-dev
      PMA_USER: root
      PMA_PORT: 3320
      UPLOAD_LIMIT: 300M
    networks:
      - fcs

  phpmyadmin-test:
    depends_on:
      - database-test
    image: phpmyadmin/phpmyadmin
    container_name: fcs.phpmyadmin.test
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database-test
      PMA_USER: root
      PMA_PORT: 3321
      UPLOAD_LIMIT: 300M
    networks:
      - fcs

volumes:
  db-dev-data:

networks:
  fcs:
    name: fcs
    driver: bridge
