version: '3'

services:

  web:
    image: webdevops/php-nginx:8.1
    container_name: fcs-web
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/webroot
    volumes:
      - ./:/var/www/html
      - ./config/docker-dev/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "8001:80"

  database:
    image: mysql:8.0
    container_name: fcs-database
    restart: always
    tmpfs: /var/lib/mysql:exec,size=1G
    ports:
     - '3310:3306'
    environment:
      MYSQL_DATABASE: foodcoopshop
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TCP_PORT: 3310
    volumes:
      - ./config/sql/_installation/clean-db-structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./tests/config/sql/test-db-data.sql:/docker-entrypoint-initdb.d/2.sql

  phpmyadmin:
    depends_on:
     - database
    image: phpmyadmin/phpmyadmin
    container_name: fcs-phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_PORT: 3310
      UPLOAD_LIMIT: 300M

  composer:
    container_name: fcs-composer
    image: composer:latest
    restart: 'no'
    volumes:
      - ./:/var/www/html
  
  node:
    container_name: fcs-node
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
