#The provided docker should NOT BE USED IN PRODUCTION ENVIRONMENTS!

version: '3'

services:

  php-nginx:
    build: ./config/docker-dev/php-nginx
    container_name: fcs-php-nginx
    restart: always
    user: ${CURRENT_UID}
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/webroot
    volumes:
      - ./:/var/www/html
      - ./config/docker-dev/php-nginx/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "8001:80"
    depends_on:
      - database-dev
    networks:
      - fcs

  database-dev:
    image: mysql:8.0
    container_name: fcs-database-dev
    restart: always
    ports:
      - '3310:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: foodcoopshop-dev
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3310
    volumes:
      - db-dev-data:/var/lib/mysql
    networks:
      - fcs

  database-test:
    image: mysql:8.0
    container_name: fcs-database-test
    restart: always
    tmpfs: /var/lib/mysql:exec,size=1G #smaller size (eg. 256M) lead to failing tests
    ports:
      - '3311:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: foodcoopshop-test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3311
    networks:
      - fcs

  phpmyadmin-dev:
    depends_on:
      - database-dev
    image: phpmyadmin/phpmyadmin
    container_name: fcs-phpmyadmin-dev
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database-dev
      PMA_USER: root
      PMA_PORT: 3310
      UPLOAD_LIMIT: 300M
    networks:
      - fcs

  phpmyadmin-test:
    depends_on:
      - database-test
    image: phpmyadmin/phpmyadmin
    container_name: fcs-phpmyadmin-test
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database-test
      PMA_USER: root
      PMA_PORT: 3311
      UPLOAD_LIMIT: 300M
    networks:
      - fcs

volumes:
  db-dev-data:


networks:
  fcs:
