version: '3'

services:

  php-nginx:
    image: webdevops/php-nginx:8.1
    container_name: fcs-php-nginx
    restart: always
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/webroot
    volumes:
      - ./:/var/www/html
      - ./config/docker-dev/php-nginx/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "8001:80"
    depends_on:
      - database
    networks:
      - fcs
      
  database:
    image: mysql:8.0
    container_name: fcs-database
    restart: always
    tmpfs: /var/lib/mysql:exec,size=1G
    ports:
     - '3310:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: foodcoopshop
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3310
    volumes:
      - ./config/sql/_installation/clean-db-structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./tests/config/sql/test-db-data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - fcs

  phpmyadmin:
    depends_on:
     - database
    image: phpmyadmin/phpmyadmin
    container_name: fcs-phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PORT: 3310
      UPLOAD_LIMIT: 300M
    networks:
      - fcs
      
  composer:
    container_name: fcs-composer
    image: composer:latest
    entrypoint: ['composer', '--ignore-platform-reqs']
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
  
  node:
    container_name: fcs-node
    build: ./config/docker-dev/node 
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - fcs

networks:
  fcs:
