version: '3'

services:
  web:
    image: nginx:latest
    container_name: fcs-nginx   
    ports:
      - "8001:80"
    volumes:
      - ./config/docker-dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  php:
    container_name: fcs-php
    build:
      context: .
      dockerfile: ./config/docker-dev/php/Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./config/docker-dev/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  database:
    image: mysql:8.0
    container_name: fcs-database
    restart: always
    ports:
     - '6603:3306'
    environment:
      MYSQL_DATABASE: foodcoopshop_dev
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./config/sql/_installation/clean-db-structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./config/sql/_installation/clean-db-data-de_DE.sql:/docker-entrypoint-initdb.d/2.sql

  phpmyadmin:
    depends_on:
     - database
    image: phpmyadmin/phpmyadmin
    container_name: fcs-phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      PMA_HOST: database