TRUNCATE TABLE `fcs_carts`;
TRUNCATE TABLE `fcs_cart_products`;
TRUNCATE TABLE `fcs_cart_product_units`;
TRUNCATE TABLE `fcs_invoices`;
TRUNCATE TABLE `fcs_invoice_taxes`;
TRUNCATE TABLE `fcs_order_detail`;
TRUNCATE TABLE `fcs_order_detail_feedbacks`;
TRUNCATE TABLE `fcs_order_detail_purchase_prices`;
TRUNCATE TABLE `fcs_order_detail_units`;
TRUNCATE TABLE `fcs_payments`;
DELETE FROM `fcs_action_logs` WHERE `type` LIKE 'payment_%';
DELETE FROM `fcs_action_logs` WHERE `type` = 'customer_order_finished';
