#!/usr/bin/env bash
# get the script dir
DIR=`php -r "echo dirname(realpath('$0'));"`

######################################
#
# HOW TO CREATE NEW DATABASE DUMPS (if a new migration was created)
#  
# 1) rename database in default db config to "foodcoopshop_tmp" or whatever name
# 3) run devtools/db_dump_all - triggers error on first call as "foodcoopshop_tmp" does not exist yet. just ignore.
# 4) rename database in default db config to initial name
# 5) commit the modified database dumps
# 
######################################


source $(dirname $0)/locales.sh
for locale in "${LOCALES[@]}"
do
    php -f $DIR/db_dump_install.php $locale
done

php -f $DIR/db_dump_test.php de_DE
