#!/usr/bin/env bash
# get the script dir
DIR=`php -r "echo dirname(realpath('$0'));"`

# run the real script
source $(dirname $0)/locales.sh
for locale in "${LOCALES[@]}"
do
    php -f $DIR/db_dump_install.php $locale
done
