#!/usr/bin/env bash
# get the script dir
DIR=`php -r "echo dirname(realpath('$0'));"`

source $(dirname $0)/locales.sh
for locale in "${LOCALES[@]}"
do
    php -f $DIR/db_dump_install.php $locale
done

php -f $DIR/db_dump_test.php de_DE
