#!/usr/bin/env bash

# the version controlled git hook script
SCRIPT="devtools/git-pre-commit.sh"

# get the project dir from being in [project]/.git/hooks/ and change to it
DIR=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`

RESULT=1
if [ -f "$DIR/$SCRIPT" ] ; then
    exec "$DIR/$SCRIPT"
    RESULT=$?
fi

exit $RESULT
