<?php
declare(strict_types=1);

use Cake\I18n\I18n;
use Migrations\AbstractMigration;

class AddRegistrierkasseApi extends AbstractMigration
{
    public function change()
    {

        switch(I18n::getLocale()) {
            case 'de_DE':
                $text = 'Schnittstelle (API) zu Registrierkasse HelloCash (hellocash.at) aktivieren?<div class="small">Alle Rechnungen (bar und unbar) über die Registrierkasse erstellen.</div>';
                break;
            default:
                $text = 'Enable API to hellocash.at?<div class="small">Invoices (cash and cashless) are generated by hellocash.at.</div>';
                break;
        }
        $sql = "INSERT INTO `fcs_configuration` (`id_configuration`, `active`, `name`, `text`, `value`, `type`, `position`, `locale`, `date_add`, `date_upd`) VALUES (NULL, '1', 'FCS_HELLO_CASH_API_ENABLED', '".$text."', '0', 'readonly', '583', '".I18n::getLocale()."', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);";
        $this->execute($sql);

        $this->execute("UPDATE fcs_configuration SET position = 584 WHERE name ='FCS_PURCHASE_PRICE_ENABLED';");

        $this->execute("ALTER TABLE `fcs_customer` ADD `user_id_registrierkasse` INT(10) UNSIGNED NULL DEFAULT 0 AFTER `use_camera_for_barcode_scanning`;");

    }
}
