name: FoodCoopShop Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: FoodCoopShop Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Docker Compose
        run: CURRENT_UID=$(id -u):$(id -g) docker compose up -d
        
      - name: Setup Dev Environment
        run: bash ./devtools/init-dev-setup.sh
        
      - name: Apply secrets
        run: |
          sed -i 's/HELLO_CASH_USERNAME/${{secrets.HELLO_CASH_USERNAME}}/' ./config/custom_config.php
          sed -i 's/HELLO_CASH_PASSWORD/${{secrets.HELLO_CASH_PASSWORD}}/' ./config/custom_config.php
          sed -i 's/HELLO_CASH_CASHIER_ID/${{secrets.HELLO_CASH_CASHIER_ID}}/' ./config/custom_config.php

      - name: PHPUnit Tests
        run: docker exec -w /var/www/html fcs-php-nginx php ./vendor/bin/phpunit
