name: FoodCoopShop Tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    
      - name: Checkout code
      - uses: actions/checkout@v2
      
     - name: Run Docker Compose
       run: CURRENT_UID=$(id -u):$(id -g) docker compose up -d
        
     - name: PHPUnit Tests
       wait-on: http://localhost:8001
       start: docker exec -w /var/www/html fcs-php-nginx php ./vendor/bin/phpunit
          
